import gzip
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CORPUS = ROOT / "apps/mobile/assets/bibles/kjv"
DIRECTION = ROOT / "apps/mobile/assets/bible_direction/kjv"
REGISTRY = ROOT / "editorial-review/registry.kjv.json"

# Every entry below names one reviewed occurrence in Exodus. Nothing is found or
# replaced globally. Common KJV grammar and disputed theological wording stay
# unchanged unless the complete phrase has one clear modern reading.
CHANGES = [
    (1, 5, "souls that came out of the loins of Jacob were seventy souls", "people descended from Jacob were seventy people", "archaic-genealogy", "Loins denotes physical descent; people avoids the misleading modern sense of disembodied souls."),
    (1, 7, "waxed exceeding mighty", "became exceedingly powerful", "archaic-verb", "Waxed means became in this population-growth statement."),
    (1, 8, "which knew not Joseph", "who did not know Joseph", "archaic-grammar", "The clause describes a king with no knowledge of Joseph."),
    (1, 10, "when there falleth out any war", "if war breaks out", "archaic-phrase", "Falleth out means occurs or breaks out."),
    (1, 11, "treasure cities", "storage cities", "false-friend", "Treasure cities were supply or storage centers, not cities made of treasure."),
    (1, 13, "serve with rigour", "serve harshly", "archaic-lexicon", "Rigour describes harsh treatment."),
    (1, 14, "was with rigour", "was harsh", "archaic-lexicon", "Rigour describes the harshness of the forced labor."),
    (1, 16, "see them upon the stools", "see them on the birthstools", "historical-object", "The stools are the birthing seats used during delivery."),
    (1, 17, "men children", "male children", "archaic-phrase", "Men children means male children in this command."),
    (1, 18, "men children", "male children", "archaic-phrase", "Men children means male children in Pharaoh's question."),
    (1, 19, "they are lively, and are delivered ere", "they are vigorous and give birth before", "archaic-birth-phrase", "Lively means vigorous and ere means before."),
    (1, 20, "waxed very mighty", "grew very powerful", "archaic-verb", "Waxed means became or grew."),
    (2, 2, "bare a son", "gave birth to a son", "archaic-verb", "Bare is the historical past tense of bear in childbirth."),
    (2, 2, "a goodly child", "a beautiful child", "archaic-adjective", "Goodly describes the child's fine appearance."),
    (2, 3, "an ark of bulrushes", "a basket of papyrus reeds", "historical-object", "Ark here is a small basket, and bulrushes are papyrus reeds."),
    (2, 3, "daubed it with slime and with pitch", "coated it with bitumen and pitch", "historical-material", "Slime here is bitumen used to waterproof the basket."),
    (2, 3, "in the flags by the river’s brink", "among the reeds by the riverbank", "archaic-geography", "Flags are reeds and brink is the bank's edge."),
    (2, 4, "to wit what would be done to him", "to see what would happen to him", "archaic-idiom", "To wit means to know or find out."),
    (2, 11, "smiting an Hebrew", "beating a Hebrew", "archaic-verb", "Smiting describes the Egyptian striking the Hebrew."),
    (2, 12, "slew the Egyptian", "killed the Egyptian", "archaic-verb", "Slew means killed."),
    (2, 13, "two men of the Hebrews strove together", "two Hebrew men were fighting", "archaic-verb", "Strove together means fought with each other."),
    (2, 13, "Wherefore smitest thou thy fellow?", "Why are you striking your fellow?", "archaic-question", "The full question is modernized without changing its accusation."),
    (2, 14, "intendest thou to kill me, as thou killedst", "do you intend to kill me, as you killed", "archaic-grammar", "The coordinated verb phrase removes obsolete second-person endings."),
    (2, 15, "sought to slay Moses", "tried to kill Moses", "archaic-verb", "Sought to slay means tried to kill."),
    (2, 21, "was content to dwell with the man", "agreed to live with the man", "archaic-idiom", "Content here means willing or agreeable, not merely satisfied."),
    (2, 22, "she bare him a son", "she gave birth to his son", "archaic-verb", "Bare means gave birth."),
    (2, 23, "in process of time", "after many years", "archaic-time-phrase", "The phrase indicates the passage of a long period."),
    (2, 25, "had respect unto them", "took notice of them", "archaic-idiom", "Had respect unto describes God's attention to Israel's condition."),
    (3, 1, "the backside of the desert", "the far side of the wilderness", "false-friend-geography", "Backside means the far side, and desert here is wilderness."),
    (3, 5, "Draw not nigh hither", "Do not come any closer", "archaic-direction", "The command forbids Moses from approaching further."),
    (3, 18, "hearken to thy voice", "listen to your voice", "archaic-verb", "Hearken means listen."),
    (3, 18, "we beseech thee", "we ask you", "archaic-verb", "Beseech means earnestly ask."),
    (3, 22, "borrow of her neighbour", "ask her neighbour for", "false-friend", "Borrow has the historical sense of ask or request here; the following verse says the items were given."),
    (3, 22, "of her that sojourneth in her house", "from the woman staying in her house", "archaic-verb", "Sojourneth means is temporarily staying."),
    (3, 22, "jewels of silver, and jewels of gold, and raiment", "articles of silver, articles of gold, and clothing", "historical-objects", "Jewels can mean valuable articles generally, and raiment means clothing."),
    (4, 6, "into thy bosom", "inside your cloak", "historical-clothing", "Bosom here is the fold inside Moses' outer garment."),
    (4, 7, "plucked it out of his bosom", "pulled it out of his cloak", "archaic-action", "The phrase describes withdrawing his hand from the garment fold."),
    (4, 8, "the latter sign", "the second sign", "archaic-sequence", "Latter contrasts the second sign with the first."),
    (4, 10, "neither heretofore", "neither before", "archaic-time-adverb", "Heretofore means before now."),
    (4, 11, "maketh the dumb", "makes a person unable to speak", "historical-disability-language", "Dumb here means unable to speak."),
    (4, 14, "the anger of the LORD was kindled", "the anger of the LORD burned", "archaic-idiom", "Kindled figuratively describes anger burning."),
    (4, 19, "which sought thy life", "who wanted to kill you", "archaic-idiom", "Seeking someone's life means attempting to kill that person."),
    (4, 20, "upon an ass", "on a donkey", "archaic-animal-name", "Ass is the historical English name for a donkey."),
    (5, 1, "hold a feast unto me", "celebrate a feast for me", "archaic-idiom", "Hold a feast unto means celebrate a feast in honor of the LORD."),
    (5, 3, "with pestilence", "with plague", "archaic-lexicon", "Pestilence means a deadly epidemic or plague."),
    (5, 4, "Wherefore do ye, Moses and Aaron, let the people from their works?", "Why do you, Moses and Aaron, stop the people from their work?", "false-friend", "Let here means hinder or stop, the opposite of its usual modern sense."),
    (5, 7, "as heretofore", "as before", "archaic-time-adverb", "Heretofore means previously."),
    (5, 8, "the tale of the bricks", "the quota of bricks", "false-friend", "Tale here means a required count or quota."),
    (5, 8, "not diminish ought thereof", "not reduce any of it", "archaic-quantity", "Ought means anything in this negative construction."),
    (5, 11, "not ought of your work", "none of your work", "archaic-quantity", "Not ought means none."),
    (5, 13, "hasted them", "pressed them", "archaic-verb", "Hasted describes the taskmasters driving the workers urgently."),
    (5, 18, "deliver the tale of bricks", "produce the quota of bricks", "false-friend", "Tale means the required count."),
    (5, 19, "were in evil case", "were in serious trouble", "archaic-idiom", "Evil case means a difficult or dangerous situation."),
    (5, 21, "made our savour to be abhorred", "made us repulsive", "archaic-idiom", "The smell metaphor means Pharaoh and his servants now regard them with disgust."),
    (5, 22, "so evil entreated this people", "treated this people so badly", "archaic-verb", "Evil entreated means mistreated."),
    (6, 6, "rid you out of their bondage", "free you from their bondage", "archaic-verb", "Rid out means deliver or free."),
    (6, 8, "give it you for an heritage", "give it to you as an inheritance", "archaic-noun", "Heritage means an inherited possession."),
    (6, 9, "for anguish of spirit", "because of their broken spirit", "archaic-phrase", "The phrase describes the people's crushing discouragement under slavery."),
    (7, 7, "fourscore years old", "eighty years old", "archaic-number", "Fourscore equals eighty."),
    (7, 7, "fourscore and three years old", "eighty-three years old", "archaic-number", "Fourscore and three equals eighty-three."),
    (7, 15, "against he come", "to meet him", "archaic-direction", "Against he come means positioned to meet him as he arrives."),
    (7, 16, "hitherto thou wouldest not hear", "until now you have refused to listen", "archaic-phrase", "Hitherto means until now; hear here means heed."),
    (7, 18, "shall lothe to drink", "will be unable to bear drinking", "archaic-verb", "Lothe here describes finding the river water intolerable."),
    (7, 24, "digged round about", "dug all around", "archaic-verb", "Digged is the historical past tense of dig."),
    (8, 3, "kneadingtroughs", "kneading bowls", "historical-object", "Kneading troughs were containers used to prepare dough."),
    (8, 8, "Intreat the LORD", "Plead with the LORD", "archaic-verb", "Intreat means plead or appeal."),
    (8, 9, "Glory over me: when shall I intreat", "You choose the time: when shall I plead", "opaque-idiom", "Moses gives Pharaoh the honor of choosing when the prayer will be made."),
    (8, 15, "there was respite", "there was relief", "archaic-noun", "Respite means a temporary relief."),
    (8, 22, "I will sever in that day", "I will set apart on that day", "archaic-verb", "Sever here means distinguish or set apart Goshen."),
    (8, 24, "a grievous swarm", "a severe swarm", "archaic-adjective", "Grievous describes the swarm's severity."),
    (8, 26, "It is not meet so to do", "It is not right to do so", "archaic-adjective", "Meet means fitting or proper."),
    (8, 26, "the abomination of the Egyptians", "what the Egyptians consider detestable", "opaque-cultural-phrase", "The phrase describes sacrifices the Egyptians would find offensive."),
    (8, 28, "intreat for me", "plead for me", "archaic-verb", "Intreat means plead."),
    (8, 29, "intreat the LORD", "plead with the LORD", "archaic-verb", "Intreat means plead."),
    (8, 30, "intreated the LORD", "pleaded with the LORD", "archaic-verb", "Intreated means pleaded."),
    (9, 3, "upon the asses", "upon the donkeys", "archaic-animal-name", "Asses means donkeys."),
    (9, 3, "a very grievous murrain", "a very severe plague", "obsolete-disease-name", "Murrain is an obsolete word for a deadly livestock disease."),
    (9, 9, "a boil breaking forth with blains", "festering boils", "obsolete-medical-phrase", "Blains are inflammatory sores; the phrase describes erupting boils."),
    (9, 10, "a boil breaking forth with blains", "festering boils", "obsolete-medical-phrase", "Blains are inflammatory sores; the phrase describes erupting boils."),
    (9, 16, "in very deed for this cause", "for this very reason", "archaic-phrase", "In very deed emphasizes the stated purpose."),
    (9, 31, "the barley was in the ear, and the flax was bolled", "the barley had formed heads, and the flax was in bloom", "obsolete-agriculture", "In the ear describes grain heads and bolled describes flax in bloom."),
    (9, 32, "the wheat and the rie", "the wheat and the spelt", "historical-grain-name", "Rie here represents the grain commonly identified as spelt."),
    (10, 2, "what things I have wrought in Egypt", "what I have done in Egypt", "archaic-verb", "Wrought means done."),
    (10, 4, "locusts into thy coast", "locusts into your territory", "false-friend-geography", "Coast means territory or region, not only seashore."),
    (10, 5, "the residue of that which is escaped", "the remainder that survived", "archaic-phrase", "Residue is the remainder and escaped means survived the hail."),
    (10, 17, "intreat the LORD", "plead with the LORD", "archaic-verb", "Intreat means plead."),
    (10, 18, "intreated the LORD", "pleaded with the LORD", "archaic-verb", "Intreated means pleaded."),
    (10, 24, "your herds be stayed", "your herds remain behind", "archaic-verb", "Stayed here means left behind."),
    (10, 26, "not an hoof be left behind", "not one hoof be left behind", "archaic-article", "The modern construction is not one hoof."),
    (11, 1, "go hence", "go from here", "archaic-direction", "Hence means from here."),
    (11, 1, "thrust you out hence altogether", "drive you out from here completely", "archaic-phrase", "The full phrase describes Pharaoh expelling the people without reservation."),
    (11, 2, "borrow of his neighbour", "ask his neighbour for", "false-friend", "Borrow has the historical sense of ask for in this passage."),
    (11, 2, "jewels of silver, and jewels of gold", "articles of silver and articles of gold", "historical-objects", "Jewels can mean valuable articles generally."),
    (11, 7, "shall not a dog move his tongue", "not even a dog will bark", "archaic-idiom", "The idiom emphasizes complete peace among the Israelites."),
    (12, 3, "a lamb for an house", "a lamb for each household", "archaic-article", "The instruction assigns one lamb to each household."),
    (12, 4, "according to the number of the souls", "according to the number of people", "archaic-noun", "Souls here means people in the household."),
    (12, 7, "the two side posts and on the upper door post", "the two doorposts and the lintel", "historical-architecture", "These are the sides and upper crosspiece of the doorway."),
    (12, 9, "nor sodden at all with water", "nor boiled in water", "obsolete-cooking-verb", "Sodden is the historical past participle of seethe, meaning boiled."),
    (12, 9, "with the purtenance thereof", "with its internal organs", "obsolete-anatomy", "Purtenance denotes the animal's internal organs."),
    (12, 11, "with your loins girded", "with your belts fastened", "archaic-clothing-idiom", "Girded loins describes clothing secured for immediate travel."),
    (12, 16, "an holy convocation", "a sacred assembly", "archaic-religious-phrase", "Convocation means an assembly called together."),
    (12, 16, "save that which every man must eat", "except what each person must eat", "archaic-exception", "Save means except."),
    (12, 17, "this selfsame day", "this very day", "archaic-emphasis", "Selfsame means the very same."),
    (12, 18, "on the fourteenth day of the month at even, ye shall eat unleavened bread, until the one and twentieth day of the month at even", "on the fourteenth day of the month in the evening, you shall eat unleavened bread, until the twenty-first day of the month in the evening", "archaic-time-and-number", "The complete span preserves both evening boundaries and expresses one-and-twentieth as twenty-first."),
    (12, 22, "the bason", "the basin", "archaic-spelling", "Bason is the historical spelling of basin."),
    (12, 23, "will not suffer the destroyer", "will not allow the destroyer", "false-friend", "Suffer here means allow."),
    (12, 31, "get you forth from among my people", "get out from among my people", "archaic-direction", "Get you forth means depart."),
    (12, 33, "were urgent upon the people", "urged the people", "archaic-idiom", "Were urgent upon means pressed them to leave."),
    (12, 35, "borrowed of the Egyptians", "asked the Egyptians for", "false-friend", "Borrowed has the historical sense of requested."),
    (12, 35, "jewels of silver, and jewels of gold, and raiment", "articles of silver, articles of gold, and clothing", "historical-objects", "Jewels can mean articles and raiment means clothing."),
    (12, 36, "lent unto them such things as they required", "gave them what they requested", "archaic-transaction-phrase", "The Egyptians granted the requested articles rather than creating ordinary loans."),
    (12, 39, "could not tarry", "could not delay", "archaic-verb", "Tarry means remain or delay."),
    (12, 39, "any victual", "any provisions", "obsolete-noun", "Victual means food or provisions."),
    (12, 41, "the hosts of the LORD", "the divisions of the LORD", "archaic-military-noun", "Hosts here describes the organized divisions leaving Egypt."),
    (12, 42, "a night to be much observed", "a night of solemn observance", "archaic-phrase", "The phrase identifies a night to be commemorated faithfully."),
    (12, 45, "an hired servant", "a hired worker", "archaic-grammar", "Hired servant denotes a contracted worker."),
    (12, 46, "carry forth ought of the flesh abroad", "carry any of the meat outside", "archaic-quantity", "Ought means any, and abroad here means outside the house."),
    (12, 49, "him that is homeborn", "the native-born person", "archaic-legal-term", "Homeborn means native-born."),
    (13, 7, "in all thy quarters", "throughout your territory", "false-friend-geography", "Quarters here means the territory where the people live."),
    (13, 10, "in his season", "at its appointed time", "archaic-time-phrase", "Season here is the appointed annual time."),
    (13, 12, "all that openeth the matrix", "every firstborn that opens the womb", "obsolete-anatomy", "Matrix is the historical anatomical term for womb."),
    (13, 13, "firstling of an ass", "firstborn donkey", "archaic-animal-phrase", "Firstling means firstborn and ass means donkey."),
    (13, 15, "would hardly let us go", "stubbornly refused to let us go", "false-friend", "Hardly here describes Pharaoh's stubborn refusal, not a narrow possibility."),
    (13, 15, "all that openeth the matrix", "every firstborn that opens the womb", "obsolete-anatomy", "Matrix is the historical anatomical term for womb."),
    (13, 16, "for frontlets between thine eyes", "as a reminder on your forehead", "historical-object", "Frontlets describe a visible reminder associated with the forehead."),
    (13, 17, "Lest peradventure the people repent", "Perhaps the people will change their minds", "false-friend", "Repent here means change course and return to Egypt; peradventure means perhaps."),
    (13, 19, "straitly sworn", "made to swear solemnly", "archaic-idiom", "Straitly intensifies the seriousness of the oath."),
    (14, 4, "be honoured upon Pharaoh", "gain honor through Pharaoh", "archaic-idiom", "The phrase describes the LORD displaying his glory through judgment on Pharaoh."),
    (14, 8, "went out with an high hand", "went out boldly", "archaic-idiom", "A high hand describes open, confident defiance rather than a physical gesture."),
    (14, 10, "were sore afraid", "were terrified", "archaic-intensifier", "Sore intensifies their fear."),
    (14, 14, "hold your peace", "remain silent", "archaic-idiom", "Hold your peace means remain silent."),
    (14, 17, "get me honour upon Pharaoh", "gain honor through Pharaoh", "archaic-idiom", "The phrase describes the LORD displaying his glory through judgment."),
    (14, 18, "gotten me honour upon Pharaoh", "gained honor through Pharaoh", "archaic-idiom", "The phrase describes glory displayed through Pharaoh's defeat."),
    (14, 24, "the host of the Egyptians", "the army of the Egyptians", "archaic-military-noun", "Host here means army."),
    (14, 25, "drave them heavily", "drove them with difficulty", "archaic-verb", "Drave is an old past tense of drive; heavily describes the impeded chariots."),
    (14, 28, "all the host of Pharaoh", "all the army of Pharaoh", "archaic-military-noun", "Host here means army."),
    (15, 4, "Pharaoh’s chariots and his host", "Pharaoh’s chariots and his army", "archaic-military-noun", "Host here means army."),
    (15, 6, "hath dashed in pieces the enemy", "has shattered the enemy", "archaic-phrase", "Dashed in pieces means shattered."),
    (15, 7, "in the greatness of thine excellency", "in the greatness of your majesty", "archaic-noun", "Excellency here denotes divine majesty."),
    (15, 8, "the depths were congealed", "the depths became firm", "archaic-verb", "Congealed describes the waters becoming fixed or firm."),
    (15, 9, "my lust shall be satisfied upon them", "my desire shall be satisfied upon them", "false-friend", "Lust here means strong desire, not specifically sexual desire."),
    (15, 15, "the dukes of Edom", "the chiefs of Edom", "historical-title", "Dukes here are tribal chiefs, not later European nobles."),
    (15, 16, "still as a stone", "motionless as a stone", "false-friend", "Still describes being unable to move."),
    (15, 25, "there he proved them", "there he tested them", "false-friend", "Proved means tested."),
    (15, 27, "threescore and ten palm trees", "seventy palm trees", "archaic-number", "Threescore and ten equals seventy."),
    (16, 3, "the flesh pots", "the pots of meat", "archaic-word-order", "Flesh pots were pots in which meat was cooked."),
    (16, 4, "gather a certain rate every day", "gather each day's portion", "archaic-quantity-phrase", "Rate here means an allotted daily amount."),
    (16, 4, "that I may prove them", "that I may test them", "false-friend", "Prove means test."),
    (16, 6, "At even", "In the evening", "archaic-time", "Even means evening."),
    (16, 12, "At even", "In the evening", "archaic-time", "Even means evening."),
    (16, 13, "round about the host", "all around the camp", "archaic-military-noun", "Host here means the encampment."),
    (16, 14, "the hoar frost", "frost", "archaic-weather-term", "Hoar frost means a white frost."),
    (16, 18, "did mete it", "measured it", "archaic-verb", "Mete means measure."),
    (16, 20, "Moses was wroth", "Moses was angry", "archaic-adjective", "Wroth means angry."),
    (16, 21, "the sun waxed hot", "the sun grew hot", "archaic-verb", "Waxed means became or grew."),
    (16, 23, "seethe that ye will seethe", "boil what you will boil", "obsolete-cooking-verb", "Seethe means boil."),
    (16, 24, "as Moses bade", "as Moses instructed", "archaic-verb", "Bade means instructed or commanded."),
    (16, 29, "abide ye every man in his place", "each of you remain in your place", "archaic-verb", "Abide here means remain."),
    (17, 1, "pitched in Rephidim", "camped in Rephidim", "archaic-travel-verb", "Pitched means set up camp."),
    (17, 2, "did chide with Moses", "quarreled with Moses", "archaic-verb", "Chide here means contend or quarrel."),
    (17, 2, "wherefore do ye tempt the LORD?", "why do you test the LORD?", "false-friend", "Tempt here means put to the test."),
    (17, 7, "because of the chiding", "because of the quarrelling", "archaic-noun", "Chiding here means contention."),
    (17, 7, "they tempted the LORD", "they tested the LORD", "false-friend", "Tempted here means put to the test."),
    (17, 12, "stayed up his hands", "supported his hands", "archaic-verb", "Stayed up means supported."),
    (17, 13, "discomfited Amalek", "defeated Amalek", "obsolete-verb", "Discomfited means defeated, not merely made uncomfortable."),
    (17, 14, "rehearse it in the ears of Joshua", "recite it to Joshua", "archaic-idiom", "Rehearse here means recount or recite."),
    (18, 7, "did obeisance", "bowed down", "archaic-noun", "Obeisance is a respectful bow."),
    (18, 8, "all the travail", "all the hardship", "false-friend", "Travail here means hardship, not childbirth."),
    (18, 13, "on the morrow", "the next day", "archaic-time", "Morrow means the next day."),
    (18, 14, "from morning unto even", "from morning until evening", "archaic-time", "Even means evening."),
    (18, 15, "to enquire of God", "to seek guidance from God", "archaic-spelling-and-idiom", "Enquire means seek an answer or guidance."),
    (18, 18, "wilt surely wear away", "will surely wear yourselves out", "archaic-idiom", "Wear away describes exhaustion from the workload."),
    (18, 19, "to God-ward", "as the people's representative before God", "opaque-directional-phrase", "God-ward describes Moses' representative role before God."),
    (18, 21, "hating covetousness", "hating dishonest gain", "false-friend", "Covetousness in this leadership qualification concerns corrupt gain."),
    (18, 26, "the hard causes", "the difficult cases", "archaic-legal-noun", "Causes here means legal cases."),
    (19, 5, "a peculiar treasure", "a treasured possession", "false-friend", "Peculiar here means specially belonging to God, not strange."),
    (19, 11, "ready against the third day", "ready for the third day", "archaic-preposition", "Against here means in preparation for."),
    (19, 15, "come not at your wives", "do not have sexual relations with your wives", "archaic-euphemism", "Come at is a historical euphemism for sexual relations."),
    (19, 17, "the nether part of the mount", "the foot of the mountain", "archaic-geography", "Nether part means the lower part or foot."),
    (19, 18, "was altogether on a smoke", "was completely covered in smoke", "archaic-phrase", "On a smoke means enveloped in smoke."),
    (19, 21, "charge the people", "warn the people", "false-friend", "Charge here means give a solemn warning."),
    (20, 4, "any graven image", "any carved image", "archaic-adjective", "Graven means carved."),
    (20, 11, "hallowed it", "made it holy", "archaic-verb", "Hallowed means made holy."),
    (20, 20, "God is come to prove you", "God has come to test you", "false-friend", "Prove means test."),
    (20, 25, "hewn stone", "cut stone", "archaic-craft-term", "Hewn stone has been cut or shaped with tools."),
    (21, 6, 'with an aul', 'with an awl', 'archaic-spelling', 'Aul is the historical spelling of awl.'),
    (21, 7, 'to be a maidservant', 'to be a female servant', 'archaic-noun', 'Maidservant means female servant in this law.'),
    (21, 7, 'as the menservants do', 'as the male servants do', 'archaic-noun', 'Menservants means male servants.'),
    (21, 10, 'her raiment', 'her clothing', 'archaic-noun', 'Raiment means clothing.'),
    (21, 14, 'come presumptuously upon his neighbour, to slay him with guile', 'deliberately attack his neighbour and kill him by treachery', 'opaque-legal-phrase', 'The clause describes premeditated, treacherous killing.'),
    (21, 33, 'an ass fall therein', 'a donkey fall into it', 'archaic-animal-and-direction', 'Ass means donkey and therein means into it.'),
    (22, 6, 'stacks of corn, or the standing corn', 'stacks of grain, or the standing grain', 'false-friend-agriculture', 'Corn here means grain generally.'),
    (22, 7, 'money or stuff to keep', 'money or property to keep', 'false-friend', 'Stuff here means property entrusted for safekeeping.'),
    (22, 9, 'which another challengeth to be his', 'which another claims to be his', 'archaic-verb', 'Challengeth here means claims ownership.'),
    (22, 14, 'borrow ought of his neighbour', 'borrow anything from his neighbour', 'archaic-quantity', 'Ought means anything.'),
    (22, 16, 'entice a maid that is not betrothed', 'seduce an unmarried young woman', 'archaic-social-phrase', 'Maid means an unmarried young woman and entice describes seduction in context.'),
    (22, 16, 'surely endow her to be his wife', 'surely pay the bride-price for her to be his wife', 'historical-legal-term', 'Endow here refers to paying the required marriage price.'),
    (22, 18, 'suffer a witch to live', 'allow a sorceress to live', 'false-friend', 'Suffer means allow; sorceress gives the historical sense of witch.'),
    (22, 20, 'save unto the LORD only', 'except to the LORD only', 'archaic-exception', 'Save means except.'),
    (22, 21, 'neither vex a stranger', 'neither mistreat a foreigner', 'false-friend', 'Vex means mistreat and stranger means a resident foreigner here.'),
    (22, 23, 'in any wise', 'in any way', 'archaic-idiom', 'In any wise means in any way.'),
    (22, 25, 'as an usurer, neither shalt thou lay upon him usury', 'as a moneylender, nor charge him interest', 'obsolete-financial-terms', 'Usurer and usury refer here to lending at interest.'),
    (22, 26, 'thy neighbour’s raiment to pledge', 'your neighbour’s cloak as collateral', 'archaic-legal-terms', 'Raiment is the cloak and pledge is collateral.'),
    (22, 26, 'by that the sun goeth down', 'before the sun goes down', 'archaic-time-clause', 'The phrase sets sunset as the deadline.'),
    (22, 27, 'it is his raiment for his skin', 'it is his cloak for his body', 'archaic-noun', 'Raiment means clothing; the specific garment is his cloak.'),
    (22, 30, 'with his dam', 'with its mother', 'archaic-animal-term', 'Dam means the mother of an animal.'),
    (23, 13, 'be circumspect', 'be careful', 'archaic-adjective', 'Circumspect means careful.'),
    (23, 19, 'seethe a kid', 'boil a young goat', 'obsolete-cooking-and-animal', 'Seethe means boil and kid means a young goat.'),
    (23, 24, 'quite break down their images', 'completely break down their images', 'false-friend', 'Quite here means completely.'),
    (24, 6, 'put it in basons', 'put it in basins', 'archaic-spelling', 'Basons is the historical spelling of basins.'),
    (24, 14, 'Tarry ye here for us', 'Wait here for us', 'archaic-verb', 'Tarry means wait.'),
    (24, 16, 'abode upon mount Sinai', 'remained upon mount Sinai', 'archaic-verb', 'Abode means remained.'),
    (25, 5, 'shittim wood', 'acacia wood', 'obsolete-material-name', 'Shittim is the historical name for acacia wood.'),
    (25, 13, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (25, 15, 'The staves shall be in the rings', 'The poles shall remain in the rings', 'archaic-object', 'Staves are carrying poles.'),
    (25, 23, 'a table of shittim wood', 'a table of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (25, 28, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (25, 30, 'shewbread before me', 'bread of the Presence before me', 'archaic-liturgical-term', 'Shewbread is the bread displayed before the LORD.'),
    (25, 31, 'a candlestick of pure gold', 'a lampstand of pure gold', 'false-friend-object', 'Candlestick here is a multi-branched oil lampstand.'),
    (25, 31, 'his knops', 'its ornamental buds', 'obsolete-craft-term', 'Knops are ornamental buds on the lampstand.'),
    (25, 38, 'snuffdishes', 'wick trays', 'obsolete-object', 'Snuffdishes are trays for burned wick trimmings.'),
    (26, 1, 'cherubims of cunning work', 'cherubim of skilled workmanship', 'archaic-craft-phrase', 'Cunning work means skilled workmanship; cherubim is already plural.'),
    (26, 4, 'from the selvedge', 'from the edge', 'obsolete-textile-term', 'Selvedge is the finished edge of fabric.'),
    (26, 6, 'fifty taches of gold', 'fifty gold clasps', 'obsolete-object', 'Taches are clasps joining the curtains.'),
    (26, 11, 'fifty taches of brass', 'fifty bronze clasps', 'obsolete-object-and-material', 'Taches are clasps and brass here denotes bronze.'),
    (26, 15, 'shittim wood standing up', 'acacia wood standing upright', 'obsolete-material-and-grammar', 'Shittim is acacia and standing up means upright.'),
    (26, 31, 'a vail', 'a veil', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (26, 36, 'an hanging for the door', 'a curtain for the entrance', 'archaic-object', 'The hanging is the entrance curtain.'),
    (27, 1, 'altar of shittim wood', 'altar of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (27, 3, 'his basons, and his fleshhooks', 'its basins and its meat forks', 'obsolete-objects', 'Basons are basins and fleshhooks are forks used with sacrificial meat.'),
    (27, 4, 'four brasen rings', 'four bronze rings', 'archaic-material', 'Brasen means made of bronze.'),
    (27, 6, 'staves for the altar, staves of shittim wood', 'poles for the altar, poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (27, 9, 'hangings for the court', 'curtains for the courtyard', 'archaic-object', 'Hangings here are the courtyard curtains.'),
    (27, 19, 'all the pins thereof, and all the pins of the court', 'all its tent pegs, and all the courtyard pegs', 'false-friend-object', 'Pins here are tent pegs.'),
    (28, 4, 'a broidered coat, a mitre, and a girdle', 'an embroidered coat, a turban, and a sash', 'obsolete-clothing-terms', 'Broidered, mitre, and girdle name the embroidered coat, turban, and sash.'),
    (28, 6, 'with cunning work', 'with skilled workmanship', 'false-friend', 'Cunning here means skillful, not deceptive.'),
    (28, 8, 'the curious girdle', 'the skillfully woven waistband', 'false-friend-craft', 'Curious means skillfully made; the girdle is the woven waistband.'),
    (28, 11, 'set in ouches of gold', 'set in gold settings', 'obsolete-jewelry-term', 'Ouches are settings or sockets for stones.'),
    (28, 14, 'of wreathen work', 'of braided work', 'obsolete-craft-term', 'Wreathen means braided or twisted.'),
    (28, 32, 'the hole of an habergeon, that it be not rent', 'the opening of a coat of mail, so that it does not tear', 'obsolete-object-and-verb', 'A habergeon is a coat of mail; rent means torn.'),
    (28, 40, 'bonnets shalt thou make for them', 'you shall make caps for them', 'false-friend-clothing', 'Bonnets here are priestly caps.'),
    (28, 42, 'linen breeches', 'linen undergarments', 'false-friend-clothing', 'Breeches here are linen undergarments.'),
    (29, 31, 'seethe his flesh', 'boil its meat', 'obsolete-cooking-verb', 'Seethe means boil.'),
    (29, 34, 'if ought of the flesh', 'if any of the meat', 'archaic-quantity', 'Ought means any.'),
    (30, 5, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (30, 18, 'a laver of brass', 'a bronze basin', 'obsolete-object-and-material', 'A laver is a wash basin and brass here denotes bronze.'),
    (30, 25, 'after the art of the apothecary', 'as prepared by a perfumer', 'false-friend-profession', 'Apothecary here is a skilled perfumer or compounder of fragrances.'),
    (31, 9, 'all his furniture, and the laver and his foot', 'all its utensils, and the basin and its stand', 'false-friend-objects', 'Furniture means equipment; laver and foot are the basin and its stand.'),
    (32, 30, 'on the morrow', 'the next day', 'archaic-time', 'Morrow means the next day.'),
    (32, 30, 'peradventure I shall make an atonement', 'perhaps I can make atonement', 'archaic-adverb', 'Peradventure means perhaps.'),
    (33, 1, 'go up hence', 'go up from here', 'archaic-direction', 'Hence means from here.'),
    (33, 18, 'I beseech thee', 'I plead with you', 'archaic-request', 'Beseech means plead; the existing spelling review already handles shew separately.'),
    (34, 26, 'seethe a kid', 'boil a young goat', 'obsolete-cooking-and-animal', 'Seethe means boil and kid means young goat.'),
    (34, 33, 'a vail on his face', 'a veil over his face', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (35, 7, 'shittim wood', 'acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (35, 11, 'his taches', 'its clasps', 'obsolete-object', 'Taches are curtain clasps.'),
    (35, 12, 'the staves thereof', 'its carrying poles', 'archaic-object', 'Staves are carrying poles.'),
    (35, 13, 'the shewbread', 'the bread of the Presence', 'archaic-liturgical-term', 'Shewbread is the bread displayed before the LORD.'),
    (35, 14, 'The candlestick', 'The lampstand', 'false-friend-object', 'Candlestick here is a multi-branched oil lampstand.'),
    (35, 16, 'his brasen grate, his staves', 'its bronze grate, its poles', 'archaic-material-and-object', 'Brasen means bronze and staves are carrying poles.'),
    (35, 16, 'the laver and his foot', 'the basin and its stand', 'obsolete-object', 'Laver and foot mean the wash basin and its stand.'),
    (35, 18, 'The pins of the tabernacle, and the pins of the court', 'The tent pegs of the tabernacle and the pegs of the courtyard', 'false-friend-object', 'Pins here are tent pegs.'),
    (36, 3, 'to make it withal', 'to make it with', 'archaic-adverb', 'Withal means with it.'),
    (36, 7, 'For the stuff they had', 'For the material they had', 'false-friend', 'Stuff here means the supplied material.'),
    (36, 11, 'from the selvedge', 'from the edge', 'obsolete-textile-term', 'Selvedge is the finished fabric edge.'),
    (36, 13, 'fifty taches of gold', 'fifty gold clasps', 'obsolete-object', 'Taches are clasps.'),
    (36, 18, 'fifty taches of brass', 'fifty bronze clasps', 'obsolete-object-and-material', 'Taches are clasps and brass denotes bronze.'),
    (36, 20, 'shittim wood, standing up', 'acacia wood, standing upright', 'obsolete-material-and-grammar', 'Shittim is acacia and standing up means upright.'),
    (36, 35, 'a vail', 'a veil', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (36, 38, 'their chapiters and their fillets', 'their capitals and their bands', 'obsolete-architecture', 'Chapiters are column capitals and fillets are decorative bands.'),
    (37, 1, 'ark of shittim wood', 'ark of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (37, 4, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (37, 10, 'table of shittim wood', 'table of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (37, 15, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (37, 17, 'the candlestick of pure gold', 'the lampstand of pure gold', 'false-friend-object', 'Candlestick here is a multi-branched oil lampstand.'),
    (37, 25, 'incense altar of shittim wood', 'incense altar of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (37, 28, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (37, 29, 'work of the apothecary', 'work of a perfumer', 'false-friend-profession', 'Apothecary here is a perfumer.'),
    (38, 1, 'offering of shittim wood', 'offering of acacia wood', 'obsolete-material-name', 'Shittim is acacia wood.'),
    (38, 3, 'the basons, and the fleshhooks', 'the basins and the meat forks', 'obsolete-objects', 'Basons are basins and fleshhooks are meat forks.'),
    (38, 4, 'a brasen grate', 'a bronze grate', 'archaic-material', 'Brasen means bronze.'),
    (38, 6, 'staves of shittim wood', 'poles of acacia wood', 'obsolete-object-and-material', 'Staves are carrying poles and shittim is acacia.'),
    (38, 8, 'the laver of brass, and the foot of it of brass, of the lookingglasses', 'the bronze basin and its bronze stand from the mirrors', 'obsolete-objects', 'Laver is a basin, foot is its stand, and lookingglasses are mirrors.'),
    (38, 17, 'their chapiters', 'their capitals', 'obsolete-architecture', 'Chapiters are the capitals at the tops of pillars.'),
    (38, 20, 'all the pins of the tabernacle', 'all the tent pegs of the tabernacle', 'false-friend-object', 'Pins here are tent pegs.'),
    (39, 6, 'inclosed in ouches of gold, graven, as signets are graven', 'enclosed in gold settings, engraved like signet seals', 'obsolete-craft-terms', 'Ouches are settings; graven means engraved; signets are seals.'),
    (39, 15, 'of wreathen work', 'of braided work', 'obsolete-craft-term', 'Wreathen means braided.'),
    (39, 23, 'the hole of an habergeon, with a band round about the hole, that it should not rend', 'the opening of a coat of mail, with a band around the opening, so that it would not tear', 'obsolete-object-and-verb', 'A habergeon is a coat of mail and rend means tear.'),
    (39, 28, 'a mitre of fine linen, and goodly bonnets of fine linen, and linen breeches', 'a fine linen turban, fine linen caps, and linen undergarments', 'obsolete-clothing-terms', 'Mitre, bonnets, and breeches denote the priestly turban, caps, and undergarments.'),
    (39, 33, 'all his furniture, his taches', 'all its equipment and its clasps', 'false-friend-objects', 'Furniture means equipment and taches are clasps.'),
    (39, 34, 'the vail of the covering', 'the covering veil', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (39, 35, 'the staves thereof', 'its carrying poles', 'archaic-object', 'Staves are carrying poles.'),
    (39, 36, 'the shewbread', 'the bread of the Presence', 'archaic-liturgical-term', 'Shewbread is the bread displayed before the LORD.'),
    (39, 37, 'The pure candlestick', 'The pure lampstand', 'false-friend-object', 'Candlestick here is an oil lampstand.'),
    (39, 39, 'The brasen altar, and his grate of brass, his staves', 'The bronze altar, its bronze grate, and its poles', 'archaic-material-and-object', 'Brasen means bronze and staves are carrying poles.'),
    (39, 39, 'the laver and his foot', 'the basin and its stand', 'obsolete-object', 'Laver and foot mean the basin and its stand.'),
    (39, 40, 'his cords, and his pins', 'its cords and its tent pegs', 'false-friend-object', 'Pins here are tent pegs.'),
    (40, 3, 'cover the ark with the vail', 'screen the ark with the veil', 'archaic-spelling-and-verb', 'Vail is the historical spelling; cover here means screen from view.'),
    (40, 4, 'bring in the candlestick', 'bring in the lampstand', 'false-friend-object', 'Candlestick here is an oil lampstand.'),
    (40, 7, 'set the laver', 'set the basin', 'obsolete-object', 'Laver means wash basin.'),
    (40, 11, 'anoint the laver and his foot', 'anoint the basin and its stand', 'obsolete-object', 'Laver and foot mean basin and stand.'),
    (40, 20, 'set the staves on the ark', 'set the poles on the ark', 'archaic-object', 'Staves are carrying poles.'),
    (40, 21, 'the vail of the covering', 'the covering veil', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (40, 24, 'the candlestick', 'the lampstand', 'false-friend-object', 'Candlestick here is an oil lampstand.'),
    (40, 30, 'put water there, to wash withal', 'put water there for washing', 'archaic-adverb', 'Withal means with it or thereby.'),
    (40, 35, 'the cloud abode thereon', 'the cloud remained upon it', 'archaic-verb', 'Abode means remained and thereon means upon it.'),
    (22, 9, 'for ox, for ass, for sheep, for raiment', 'for ox, for donkey, for sheep, for clothing', 'archaic-object-names', 'Ass means donkey and raiment means clothing.'),
    (25, 31, 'of beaten work shall the candlestick be made', 'the lampstand shall be made of hammered work', 'false-friend-craft', 'Candlestick is an oil lampstand and beaten work means hammered work.'),
    (26, 6, 'with the taches', 'with the clasps', 'obsolete-object', 'Taches are clasps.'),
    (26, 11, 'put the taches into the loops', 'put the clasps into the loops', 'obsolete-object', 'Taches are clasps.'),
    (26, 31, 'of cunning work', 'of skilled workmanship', 'false-friend', 'Cunning here means skillful.'),
    (28, 14, 'fasten the wreathen chains to the ouches', 'fasten the braided chains to the settings', 'obsolete-craft-terms', 'Wreathen means braided and ouches are jewelry settings.'),
    (30, 18, 'and his foot also of brass, to wash withal', 'and its stand also of bronze, for washing', 'obsolete-object-and-material', 'The foot is the basin stand; brass denotes bronze; withal means with it.'),
    (34, 34, 'the vail off', 'the veil off', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (35, 12, 'the vail of the covering', 'the covering veil', 'archaic-spelling', 'Vail is the historical spelling of veil.'),
    (35, 13, 'his staves', 'its carrying poles', 'archaic-object', 'Staves are carrying poles.'),
    (36, 13, 'with the taches', 'with the clasps', 'obsolete-object', 'Taches are clasps.'),
    (36, 35, 'of cunning work', 'with skilled workmanship', 'false-friend', 'Cunning here means skillful.'),
    (37, 17, 'of beaten work made he the candlestick', 'he made the lampstand of hammered work', 'false-friend-craft', 'Candlestick is an oil lampstand and beaten work means hammered work.'),
    (37, 17, 'his knops', 'its ornamental buds', 'obsolete-craft-term', 'Knops are ornamental buds.'),
    (38, 17, 'their fillets of silver', 'their silver bands', 'obsolete-architecture', 'Fillets here are decorative bands on the pillars.'),
    (40, 30, 'set the laver', 'set the basin', 'obsolete-object', 'Laver means wash basin.'),
]

def read(path): return json.loads(path.read_text(encoding="utf-8"))
def write(path, value): path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
def sha(data): return hashlib.sha256(data).hexdigest()
def canonical(value): return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))

base = read(CORPUS / "books/EXO.json")
texts = {(c["chapter"], v["verse"]): v["text"] for c in base["chapters"] for v in c["verses"]}
direction_path = DIRECTION / "books/exo_reading_2026.kjv.v1.json"
direction = read(direction_path)
added = []
for chapter, verse, expected, replacement, category, reason in CHANGES:
    text = texts[(chapter, verse)]
    start = text.find(expected)
    if start < 0: raise RuntimeError(f"Missing EXO.{chapter}.{verse}: {expected!r}")
    end = start + len(expected)
    patch = next((x for x in direction["verses"] if x["chapter"] == chapter and x["verse"] == verse), None)
    if patch is None:
        patch = {"chapter": chapter, "verse": verse, "sourceTextSha256": sha(text.encode()), "edits": []}
        direction["verses"].append(patch)
    if patch["sourceTextSha256"] != sha(text.encode()): raise RuntimeError(f"Source hash mismatch EXO.{chapter}.{verse}")
    overlap = next((e for e in patch["edits"] if start < e["endOffset"] and end > e["startOffset"]), None)
    if overlap:
        if overlap["startOffset"] == start and overlap["endOffset"] == end and overlap["expected"] == expected and overlap["replacement"] == replacement:
            continue
        raise RuntimeError(f"Overlapping edit EXO.{chapter}.{verse}: {expected!r}")
    edit = {"startOffset": start, "endOffset": end, "expected": expected, "replacement": replacement,
            "category": category, "reason": reason,
            "evidence": [{"label": "Complete-verse KJV contextual review", "url": f"https://www.biblegateway.com/passage/?search=Exodus+{chapter}%3A{verse}&version=KJV"}]}
    patch["edits"].append(edit); patch["edits"].sort(key=lambda x: x["startOffset"]); added.append((chapter, verse, expected, replacement, category, reason))

direction["verses"].sort(key=lambda x: (x["chapter"], x["verse"]))
direction["editorialStatus"] = "approved-exodus-complete-context-v5"
direction["ownerReview"] = {"contentVersion": 5, "review": "KJV Exodus complete-context review", "requiredFullTest": True}
write(direction_path, direction)

source_path = DIRECTION / "reading_2026.package-source.json"
source = read(source_path); source["contentVersion"] = 5; source["generatedAt"] = "2026-09-11T00:00:00.000Z"; source["editorialPolicy"]["version"] = 5; write(source_path, source)
order = {read(p)["book"]: read(p)["order"] for p in (CORPUS / "books").glob("*.json")}
files = list((DIRECTION / "books").glob("*.json")); books = [read(p) for p in files]; books.sort(key=lambda b: order[b["book"]])
payload = {"books": books, "contentVersion": 5, "editorialPolicy": source["editorialPolicy"], "filterId": source["filterId"], "format": "shine-reading-filter-package", "normalizationId": source["normalizationId"], "schemaVersion": 1, "sourceCorpusSha256": source["sourceCorpusSha256"], "sourceVersionId": "KJV"}
raw = canonical(payload).encode(); compressed = gzip.compress(raw, compresslevel=9, mtime=0); packages = DIRECTION / "packages"; (packages / "reading_2026.kjv.v1.package.json.gz").write_bytes(compressed)
coverage = {"expectedBookCount": 66, "includedBookCount": 66, "changedVerseCount": sum(len(b["verses"]) for b in books), "editCount": sum(sum(len(v["edits"]) for v in b["verses"]) for b in books)}
manifest = {"format": "shine-reading-filter-manifest", "filterId": source["filterId"], "schemaVersion": 1, "contentVersion": 5, "sourceVersionId": "KJV", "sourceCorpusSha256": source["sourceCorpusSha256"], "normalizationId": source["normalizationId"], "contentSha256": sha(compressed), "sizeBytes": len(compressed), "expandedSizeBytes": len(raw), "mimeType": "application/vnd.shine.reading-filter+gzip", "generatedAt": "2026-09-11", "editorialPolicy": source["editorialPolicy"], "coverage": coverage, "books": [{"id": b["book"], "order": order[b["book"]], "sourceFile": next(p.name for p in files if read(p)["book"] == b["book"]), "sourceContentSha256": b["sourceContentSha256"], "payloadSha256": sha(canonical(b).encode()), "changedVerseCount": len(b["verses"]), "editCount": sum(len(v["edits"]) for v in b["verses"])} for b in books]}
write(packages / "reading_2026.kjv.v1.manifest.json", manifest)
registry = read(REGISTRY); registry["updatedAt"] = "2026-09-11T00:00:00.000Z"; registry["activeContentVersion"] = 5
pending_exodus = [
    {"id": "kjv-exodus-harnessed", "status": "pending-review", "scope": "Exodus 13:18", "term": "went up harnessed", "proposedOptions": ["went up in orderly ranks", "went up equipped for battle"], "reason": "The Hebrew can describe either military equipment or an ordered formation; the English should not choose one without stronger editorial evidence.", "references": [{"book": "EXO", "chapter": 13, "verse": 18}], "evidence": [{"label": "Complete-verse KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+13%3A18&version=KJV"}]},
    {"id": "kjv-exodus-gods-judges", "status": "pending-review", "scope": "Exodus 22:28", "term": "revile the gods", "proposedOptions": ["insult God", "insult the judges"], "reason": "The underlying term can be read as God or appointed judges in this legal context; changing the referent would exceed a reading clarification.", "references": [{"book": "EXO", "chapter": 22, "verse": 28}], "evidence": [{"label": "Complete-verse KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+22%3A28&version=KJV"}]},
    {"id": "kjv-exodus-liquors", "status": "pending-review", "scope": "Exodus 22:29", "term": "the first of thy ripe fruits, and of thy liquors", "proposedOptions": ["the first of your harvest and your wine", "the first of your produce and your flowing yield"], "reason": "Liquors is clearly archaic, but the precise offering represented by the term needs an editorial decision before replacement.", "references": [{"book": "EXO", "chapter": 22, "verse": 29}], "evidence": [{"label": "Complete-verse KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+22%3A29&version=KJV"}]},
    {"id": "kjv-exodus-badgers-skins", "status": "pending-review", "scope": "Exodus tabernacle passages", "term": "badgers’ skins", "proposedOptions": ["durable hides", "fine leather", "sea-cow hides"], "reason": "The animal or material behind the Hebrew term is disputed, so a confident modern species name would be misleading.", "references": [{"book": "EXO", "chapter": 25, "verse": 5}, {"book": "EXO", "chapter": 35, "verse": 7}, {"book": "EXO", "chapter": 36, "verse": 19}, {"book": "EXO", "chapter": 39, "verse": 34}], "evidence": [{"label": "Complete-verse KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+25%3A5&version=KJV"}]},
    {"id": "kjv-exodus-bloody-husband", "status": "pending-review", "scope": "Exodus 4:25-26", "term": "a bloody husband", "proposedOptions": ["a bridegroom of blood", "a husband obtained through blood"], "reason": "The ritual expression is difficult and interpretively disputed; a smooth paraphrase could conceal its ambiguity.", "references": [{"book": "EXO", "chapter": 4, "verse": 25}, {"book": "EXO", "chapter": 4, "verse": 26}], "evidence": [{"label": "Complete-passage KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+4%3A25-26&version=KJV"}]},
    {"id": "kjv-exodus-uncircumcised-lips", "status": "pending-review", "scope": "Exodus 6:12,30", "term": "uncircumcised lips", "proposedOptions": ["faltering speech", "unskilled speech"], "reason": "The metaphor concerns Moses' perceived inability to speak, but replacing it requires choosing an interpretation of the image.", "references": [{"book": "EXO", "chapter": 6, "verse": 12}, {"book": "EXO", "chapter": 6, "verse": 30}], "evidence": [{"label": "Complete-passage KJV contextual review", "url": "https://www.biblegateway.com/passage/?search=Exodus+6%3A12%2C30&version=KJV"}]},
]
pending_ids = {item["id"] for item in registry["pending"]}
registry["pending"].extend(item for item in pending_exodus if item["id"] not in pending_ids)
known = {(x["reference"], x["expected"], x["replacement"]) for x in registry["applied"]}
for chapter, verse, expected, replacement, category, reason in CHANGES:
    item = {"reference": f"EXO.{chapter}.{verse}", "expected": expected, "replacement": replacement, "category": category, "reason": reason, "evidenceUrl": f"https://www.biblegateway.com/passage/?search=Exodus+{chapter}%3A{verse}&version=KJV"}
    if (item["reference"], expected, replacement) not in known: registry["applied"].append(item)
write(REGISTRY, registry)
print(json.dumps({"added": len(added), "exodusChangedVerses": len(direction["verses"]), "exodusEdits": sum(len(v["edits"]) for v in direction["verses"]), **coverage, "contentSha256": manifest["contentSha256"]}, indent=2))
